# JVM & Performance Tuning
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:ReservedCodeCacheSize=512m -XX:+UnlockExperimentalVMOptions -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Gradle Features
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.vfs.watch=true
org.gradle.configuration-cache=false

# Android Specifics
android.useAndroidX=true
android.suppressUnsupportedCompileSdk=36
android.user.home=C\:\\Users\\markj\\.android
android.overridePathCheck=true
org.gradle.java.home=C\:\\Users\\markj\\.gradle\\jdks\\jetbrains_s_r_o_-21-amd64-windows.2
