org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -XX:+UseParallelGC -XX:+TieredCompilation
android.useAndroidX=true
android.enableJetifier=false
org.gradle.java.home=C\:\\Users\\markj\\.gradle\\jdks\\jetbrains_s_r_o_-21-amd64-windows.2
org.gradle.caching=true
org.gradle.vfs.watch=true
kotlin.incremental=false
kotlin.experimental.tryK2=false
org.gradle.parallel=true

# Bypass AGP version requirement check from dependencies
android.aarMetadata.check=false
